url: "https://kaanares10.github.io"
baseurl: "/OpenGL-Engine"

exclude:
  - third_party/
  - external/
  - build/
  - out/
  - .github/
  - CMakeFiles/
  - node_modules/
  - "CMakeCache.txt"
  - "*.vcxproj"
  - "*.sln"
  - "*.rdc"
  - "*.zip"
  - "*.mp4"

theme: null
