# .github/workflows/ci-windows.yml
name: CMake on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1) Check out the code
      - uses: actions/checkout@v4

      # 2) Configure CMake with the Visual Studio generator
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build \
          -G "Visual Studio 17 2022" \
          -A x64 \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      # 3) Build the solution
      - name: Build
        run: cmake --build ${{github.workspace}}/build \
          --config ${{env.BUILD_TYPE}}

      # 4) Run any CTest tests
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure -C ${{env.BUILD_TYPE}}
