# .github/workflows/ci-windows.yml
name: CMake on Windows (Optimized)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1) Check out the repository
      - uses: actions/checkout@v4

      # 2) Cache build dir
      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}

      # 3) Configure with Ninja Multi-Config
      - name: Configure CMake
        run: cmake -B build -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      # 4) Build in parallel
      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel 8

      # 5) Run tests
      - name: Test
        working-directory: build
        run: ctest --output-on-failure -C ${{ env.BUILD_TYPE }}

      # 6) Launch your engine to verify it starts
      - name: Launch Engine
        working-directory: build/${{ env.BUILD_TYPE }}
        run: |
          cp "${{ github.workspace }}/bin/SDL2.dll" .
          ./OpenGL-Engine.exe --help
