# .github/workflows/ci-windows.yml
name: CMake on Windows (Optimized)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: build
          key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Configure CMake
        run: cmake -B build -G "Ninja Multi-Config" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel $Env:NUMBER_OF_PROCESSORS

      - name: Test
        working-directory: build
        run: ctest --output-on-failure -C ${{ env.BUILD_TYPE }}

      - name: Launch Engine
        shell: pwsh
        run: |
          # copy the SDL2 runtime next to the exe
          Copy-Item "$Env:GITHUB_WORKSPACE\bin\SDL2.dll" `
            -Destination "$Env:GITHUB_WORKSPACE\build\${{ env.BUILD_TYPE }}"

          # switch into the Release folder and launch
          Push-Location "$Env:GITHUB_WORKSPACE\build\${{ env.BUILD_TYPE }}"
          .\OpenGL-Engine.exe --help
